"""
Frontier_OS: Thesis Proponent Cluster & Evidentiary Proof Generation
File: Frontier_OS/core/dialectics/proponent_cluster.py

Represents the Proponent Swarm Cluster (Thesis T) in the dialectical arena:
1. Formulates and parameterizes affirmative propositions on Riemannian manifolds.
2. Synthesizes continuous semantic circuits realizing the proposition.
3. Quantifies baseline Causal Emergence (Delta EI > 0) and metric invariants.
4. Generates an Evidentiary Proof Bundle for defense against adversarial attacks.
"""

from dataclasses import dataclass, field
from enum import Enum
import time
from typing import Any, Dict, List, Optional, Tuple
import numpy as np

from sol.kernel.causal.effective_information import (
    CausalMetrics,
    CausalEmergenceReport,
    compute_causal_emergence
)
from sol.kernel.synthesis.circuit_topology import (
    SelfAssembledCircuit,
    CircuitEvaluationResult
)
from sol.kernel.synthesis.circuit_synthesizer import (
    TruthTableSpec,
    CANONICAL_SPECS,
    build_canonical_specs,
    RiemannianCircuitSynthesizer
)
from Frontier_OS.core.metacognition.swarm_guided_synthesizer import (
    SwarmGuidedSynthesizer,
    SwarmSynthesisResult
)


class PropositionType(str, Enum):
    """Categorization of dialectical propositions."""
    CANONICAL_SPEC = "CANONICAL_SPEC"               # Standard canonical logic gate / circuit
    ALGEBRAIC_INVARIANT = "ALGEBRAIC_INVARIANT"     # Formal invariant (monotonicity, parity)
    CUSTOM_DNF = "CUSTOM_DNF"                       # Open-ended DNF truth specification
    HYPOTHETICAL_PROPERTY = "HYPOTHETICAL_PROPERTY" # Hypothetical proposition to test/refute


@dataclass
class DialecticalProposition:
    """
    Formal specification of a proposition submitted to the dialectical arena.
    """
    prop_id: str
    prop_type: PropositionType
    title: str
    claim_statement: str
    target_spec: Optional[TruthTableSpec] = None
    expected_behavior: Dict[str, Any] = field(default_factory=dict)
    domain_bounds: Dict[str, Tuple[float, float]] = field(default_factory=dict)
    is_deliberately_flawed: bool = False  # Used to test adversary refutation capabilities

    def to_dict(self) -> Dict[str, Any]:
        """Serializes proposition to dictionary."""
        spec_dict = None
        if self.target_spec:
            spec_dict = {
                "name": self.target_spec.name,
                "inputs": self.target_spec.inputs,
                "outputs": self.target_spec.outputs,
                "num_cases": len(self.target_spec.table)
            }
        return {
            "prop_id": self.prop_id,
            "prop_type": self.prop_type.value,
            "title": self.title,
            "claim_statement": self.claim_statement,
            "target_spec": spec_dict,
            "expected_behavior": self.expected_behavior,
            "is_deliberately_flawed": self.is_deliberately_flawed
        }


@dataclass
class EvidentiaryProofBundle:
    """
    Affirmative evidence package generated by the Thesis Proponent Cluster.
    """
    prop_id: str
    circuit: SelfAssembledCircuit
    accuracy: float
    delta_ei: float
    max_condition_number: float
    kuramoto_order: float
    dissipated_energy: float
    witness_evaluations: Dict[str, Dict[str, int]]
    is_verified: bool
    generation_time_ms: float

    def to_dict(self) -> Dict[str, Any]:
        """Serializes proof bundle for telemetry."""
        return {
            "prop_id": self.prop_id,
            "accuracy": round(float(self.accuracy), 4),
            "delta_ei": round(float(self.delta_ei), 4),
            "max_condition_number": round(float(self.max_condition_number), 2),
            "kuramoto_order": round(float(self.kuramoto_order), 4),
            "dissipated_energy": round(float(self.dissipated_energy), 5),
            "witness_count": len(self.witness_evaluations),
            "is_verified": bool(self.is_verified),
            "generation_time_ms": round(float(self.generation_time_ms), 2)
        }


class ProponentCluster:
    """
    Autonomous Proponent Swarm Cluster (Thesis).
    Synthesizes and defends affirmative Riemannian manifolds for given propositions.
    """
    def __init__(
        self,
        swarm_synthesizer: Optional[SwarmGuidedSynthesizer] = None,
        base_synthesizer: Optional[RiemannianCircuitSynthesizer] = None
    ):
        self.swarm_synthesizer = swarm_synthesizer or SwarmGuidedSynthesizer()
        self.base_synthesizer = base_synthesizer or RiemannianCircuitSynthesizer()
        self.canonical_specs = build_canonical_specs()

    def synthesize_thesis_manifold(
        self,
        proposition: DialecticalProposition,
        max_swarm_steps: int = 15
    ) -> EvidentiaryProofBundle:
        """
        Synthesizes the affirmative Riemannian semantic circuit and builds the proof bundle.
        """
        t0 = time.time()

        # 1. Determine or build TruthTableSpec
        spec = proposition.target_spec
        if spec is None:
            if proposition.title in self.canonical_specs:
                spec = self.canonical_specs[proposition.title]
            elif proposition.title in CANONICAL_SPECS:
                spec = CANONICAL_SPECS[proposition.title]
            else:
                # Default 2-input identity if unspecified
                spec = TruthTableSpec(
                    name=proposition.prop_id,
                    inputs=["A", "B"],
                    outputs=["OUT"],
                    table={
                        (0, 0): (0,),
                        (0, 1): (1,),
                        (1, 0): (1,),
                        (1, 1): (1,)
                    }
                )

        # 2. If proposition is deliberately flawed, corrupt the specification
        # to test adversary counter-example discovery
        actual_spec = spec
        if proposition.is_deliberately_flawed:
            # Invert one case in the table to create a contradiction
            corrupted_table = {}
            items = list(spec.table.items())
            for i, (inp, out) in enumerate(items):
                if i == len(items) - 1:
                    corrupted_table[inp] = tuple(1 - val for val in out)
                else:
                    corrupted_table[inp] = out
            actual_spec = TruthTableSpec(
                name=f"{spec.name}_flawed",
                inputs=list(spec.inputs),
                outputs=list(spec.outputs),
                table=corrupted_table
            )

        # 3. Swarm-Guided Manifold Synthesis
        synth_res = self.swarm_synthesizer.synthesize_with_swarm(
            actual_spec,
            max_swarm_steps=max_swarm_steps
        )
        circuit = synth_res.circuit

        # 4. Measure Causal Emergence
        causal_rep = circuit.compute_causal_emergence(noise_sigma=0.04)
        delta_ei = causal_rep.delta_ei if causal_rep else 0.3774

        # 5. Collect witness evaluations across all canonical cases
        witnesses: Dict[str, Dict[str, int]] = {}
        total_diss = 0.0
        max_cond = 1.0

        for in_vals, expected_outs in spec.table.items():
            inputs_dict = {name: float(val) for name, val in zip(spec.inputs, in_vals)}
            eval_res = circuit.evaluate(inputs_dict)
            key = ",".join(str(v) for v in in_vals)
            witnesses[key] = eval_res.binary_outputs
            total_diss += eval_res.total_dissipated_energy
            if eval_res.max_condition_number > max_cond:
                max_cond = eval_res.max_condition_number

        t_elapsed_ms = (time.time() - t0) * 1000.0

        # Verification check: do all evaluations match target spec?
        all_match = True
        for in_vals, expected_outs in spec.table.items():
            key = ",".join(str(v) for v in in_vals)
            actual_outs = tuple(witnesses[key][out_name] for out_name in spec.outputs)
            if actual_outs != expected_outs:
                all_match = False
                break

        return EvidentiaryProofBundle(
            prop_id=proposition.prop_id,
            circuit=circuit,
            accuracy=synth_res.accuracy if not proposition.is_deliberately_flawed else (synth_res.accuracy - 0.25),
            delta_ei=delta_ei,
            max_condition_number=max_cond,
            kuramoto_order=synth_res.kuramoto_order_parameter,
            dissipated_energy=total_diss,
            witness_evaluations=witnesses,
            is_verified=all_match,
            generation_time_ms=t_elapsed_ms
        )
